### PR TITLE
visc_load_pdata: Make dataVersion defunct and allow loading pdata with a non-standard name

### LINKED ISSUE #300: visc_load_pdata flexibility with nonstandard data names
visc_load_pdata doesn't work if the pdata data names don't follow the format:
[data-package-name]_name_of_data

Ideally, [data-package-name] is prefixed on all of the data objects but it's not always the case and then the common workaround is to arduously code checks manually or to bypass the hash check altogether.

I think it would be nice if the user could manually set the `pkg_name` variable.

```
visc_load_pdata <- function(.data,
                            proj_or_datapackage = "datapackage",
                            criteria = NULL,
                            pkg_name = NULL){
...

if(is.null(pkg_name)) pkg_name <- strsplit(pdata_name, "_")[[1]][1]

...
```

### PR DESCRIPTION
**Pull request by slager**
## Description

Add unit tests to cover the rest of the code branches in `visc_load_pdata()`, remove dataVersion criteria method per discussion at last VISCtemplates meeting, and allow reading in pdata with a non-standard name by way of the new optional `package` argument.

## Checklist

- [x] This PR includes unit tests
- [x] This PR establishes a new function or updates parameters in an existing function
  - [x]  The roxygen skeleton for this function has been updated using `devtools::document`
- [x] I have updated NEWS.md to describe the proposed changes

### CODE REVIEW

**Comment by slager** [comment]
Removed `dataVersion` method per discussion at last `VISCtemplates` meeting. We use data hashes instead.

**Comment by slager** [comment]
Also added some commits that should resolve #300, added unit tests, and did some further work to improve code quality.

File: R/visc_load_pdata.R [hunk 1]
```diff
@@ -30,42 +34,40 @@
...
-  } else if (nchar(criteria) != 32 &
-             !grepl(pattern = "0\\.1\\.\\d{1,2}", criteria)) {
-    warning("Ignoring criteria check. Incorrect criteria syntax provided.")
-    criteria <- NULL
-
-  }
-
+  # data() loads pdata into this environment before returning
   pdata_env <- new.env(parent = emptyenv())
+
```
Comment (mayerbry) [inline R/visc_load_pdata.R:50]:
```suggestion
proj_or_datapackage <- match.arg(proj_or_datapackage)
```

File: R/visc_load_pdata.R [hunk 2]
```diff
@@ -30,42 +34,40 @@
 #' @export
 visc_load_pdata <- function(.data,
                             proj_or_datapackage = "datapackage",
```
Comment (mayerbry) [inline R/visc_load_pdata.R]:
```suggestion
                            proj_or_datapackage = c("datapackage", "proj", "repo"),
```

**Review by mayerbry — APPROVED** [review]
Thanks for getting this updated Dave.
No comments from me, I have a minor suggestion to shore up the `proj_or_datapackage` argument input but you can ignore it
